### Register Profile
POST localhost:8080/profile/register
Content-Type: application/json

{
  "name": "Zayniddin",
  "surname": "Jumabekov",
  "login": "Zayni",
  "password": "12345"
}

### Login Profile
POST localhost:8080/profile/login
Content-Type: application/json

{
  "login": "Zayni",
  "password": "12345"
}